# version: '3.8'

services:
    # VECTOR DB
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.26.3
    ports:
    - 8080:8080
    # - 50051:50051
    volumes:
    - ./VectorDB:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-huggingface'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'justicedataset'
        
        
    # INDEX DB
  redis_index_store:
    image: redis/redis-stack:latest 
    container_name: redis_index_store
    ports:
      - "8081:8001" 
    restart: on-failure:0 
    volumes:
      - ./IndexDB:/var/lib/indexdb
    networks:
      - redisnet


    # DOCUMENT DB
  redis_document_store:
    image: redis/redis-stack:latest 
    container_name: redis_document_store
    ports:
      - "8082:8001"
    restart: on-failure:0 
    volumes:
      - ./DocumentDB:/var/lib/documentdb
    networks:
      - redisnet


    # CHAT DB
  redis_chat_store:
    image: redis/redis-stack:latest 
    container_name: redis_chat_store
    ports:
      - "8083:8001"
    restart: on-failure:0 
    volumes:
      - ./ChatDB:/var/lib/chatdb
    networks:
      - redisnet

networks:
  redisnet:
    driver: bridge
