services:
    # CHAT DB
  redis_chat_store:
    image: redis/redis-stack:latest 
    container_name: redis_chat_store
    ports:
      - "8083:8001"
    restart: on-failure:0 
    volumes:
      - ./ChatDB:/var/lib/chatdb
    networks:
      - redisnet

networks:
  redisnet:
    driver: bridge

volumes:
  redis-data:
    driver: local
